name: Jule CI
on:
  push:
    paths:
      - "examples/**/*"
      - "**/*.jule"
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  jule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name:  Install JuleC
        uses: Panquesito7/setup-jule@v1.1.3
        with:
          version: dev
          directory: .julec

      - name: Add JuleC to PATH
        run: echo "$(pwd)/.julec/julec-dev/bin" >> $GITHUB_PATH

      - name: Install JuleFmt
        run: |
          git clone https://github.com/julelang/julefmt.git --depth=1 .julefmt
          cd .julefmt
          mkdir -p bin
          julec build --opt-deadcode -o bin/julefmt ./src
          echo "$(pwd)/bin" >> $GITHUB_PATH
          cd ..

      - name: Install dependencies
        run: |
          sudo apt install -y libcurl4-openssl-dev

      - name: Run checks
        run: |
          make .PHONY

      - name: Clean up
        run: |
          rm -rf .julec .julefmt **/.*out **/bin
          make clean

      - name: Check formatting
        run: |
          git diff --quiet || { echo 'Please run `make format` and push the changes.' exit 1; }
