name: Release snapbox

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new semantic version'
        required: true
        default: 'v0.0.0'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate `CHANGELOG.md`
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --tag ${{ github.event.inputs.version }}
        env:
          OUTPUT: CHANGELOG.md

      - name:  Install JuleC
        uses: Panquesito7/setup-jule@v1.1.3
        with:
          version: dev
          directory: .julec

      - name: Add JuleC to PATH
        run: echo "$(pwd)/.julec/julec-dev/bin" >> $GITHUB_PATH

      - name: Install JuleDoc
        run: |
          git clone https://github.com/julelang/juledoc.git --depth=1 juledoc
          cd juledoc
          mkdir -p bin
          julec build --opt-deadcode -o bin/juledoc ./src
          echo "$(pwd)/bin" >> $GITHUB_PATH
          cd ..

      - name: Generate API documentation
        run: make doc

      - name: Clean up
        run: |
          make clean
          rm -rf .julec juledoc **/.*out **/bin

      - name: Commit and tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md book
          git commit -m "chore(release): prepare for ${{ github.event.inputs.version }}"
          git tag -a ${{ github.event.inputs.version }} -m "${{ github.event.inputs.version }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/adamperkowski/snapbox.git HEAD:refs/heads/main --follow-tags

  release:
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Prepare files
        run: |
          VERSION=${{ github.event.inputs.version }} make package

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: |
            snapbox ${{ github.event.inputs.version }}
            ## Major Changes
          append_body: true
          files: |
            snapbox-${{ github.event.inputs.version }}.tar.gz
            snapbox-${{ github.event.inputs.version }}.zip
          prerelease: ${{ contains(github.event.inputs.version, '-') }}
